# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: wednesday
      time: "05:00"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

      terraform:
        applies-to: version-updates
        patterns:
          - "github.com/hashicorp/*"
      metal-stack:
        applies-to: version-updates
        patterns:
          - "github.com/metal-stack*"
          - connectrpc.com/connect
          - google.golang.org/protobuf
      other:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/hashicorp/*"
          - "github.com/metal-stack*"
          - connectrpc.com/connect
          - google.golang.org/protobuf
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

      actions:
        applies-to: version-updates
        patterns:
          - "*"
