name: Licenses

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
  push:
    paths:
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  check:
    name: Check Licenses
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go install github.com/google/go-licenses@latest
      - run: make check-licenses
