name: Licenses

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
  push:
    paths:
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  check:
    name: Check Licenses
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go install github.com/google/go-licenses@latest
      - run: make check-licenses
