
name: Acceptance Tests

on:
  pull_request:
    paths:
      - '**_acc_test.go'
      - 'internal/cluster/**'
      - 'internal/public_ip/**'
      - '.github/workflows/testacc.yaml'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  build:
    name: Acceptance Test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          version: latest
      - run: make testacc
        env:
          METAL_STACK_CLOUD_API_TOKEN: ${{ secrets.METAL_STACK_CLOUD_API_TOKEN }}
