name: Acceptance Tests

on:
  pull_request:
    paths:
      - "**_acc_test.go"
      - "internal/cluster/**"
      - "internal/public_ip/**"
      - "internal/kubeconfig/**"
      - ".github/workflows/testacc.yaml"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  build:
    name: Acceptance Test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      # We need the latest version of Terraform for our documentation generation to use
      - uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_wrapper: false
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - run: make testacc
        env:
          METAL_STACK_CLOUD_API_TOKEN: ${{ secrets.METAL_STACK_CLOUD_API_TOKEN }}
